---
title: Techno-shirt
hero_image: images/banner.png
description: Leer LED's met code te besturen terwijl je een draagbaar project maakt
theme: violet
version: 3.0.0
listed: true
copyedit: true
interests: wearable-technology
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-1, community-0
technologies: electronic-components
site_areas: coderdojo, projects
hardware: electronic-components
software: ''
last_tested: '2018-06-12'
steps:
- title: Inleiding
- title: Test de LED's
- title: Stik je circuit
  completion:
  - engaged
- title: Schrijf je eigen code
- title: Kleur en licht
- title: Knipperende lampjes
- title: Animeer!
- title: Regenboogplezier
  completion:
  - internal
