---
title: टेक्नो कमीज
hero_image: images/banner.png
description: कोड के साथ LEDs को नियंत्रित किस तरह करना सीखें एक पहनने योग्य परियोजना बनाते समय
theme: violet
version: 3.0.0
listed: true
copyedit: true
interests: "wearable-technology"
curriculum: "1, design-0, programming-1, phys-comp-1, manufacture-1, community-0"
technologies: "electronic-components"
site_areas: "coderdojo, projects"
hardware: "electronic-components"
software: ""
last_tested: "2018-06-12"
steps:
  - 
    title: परिचय
  - 
    title: अपने LEDs का परीक्षण करें
  - 
    title: अपने सर्किट की सिलाई करें
  - 
    title: अपना कोड लिखें
  - 
    title: रंग और रोशनी
  - 
    title: चमकती रोशनी
  - 
    title: एनिमेट! (Animate)
  - 
    title: इन्द्रधनुष मनोरंजन
