---
title: Camiseta tecnológica
hero_image: images/banner.png
description: Aprende a controlar los LED con código mientras realizas un proyecto portátil
theme: violet
version: 3.0.0
listed: true
copyedit: true
interests: "wearable-technology"
curriculum: "1, design-0, programming-1, phys-comp-1, manufacture-1, community-0"
technologies: "electronic-components"
site_areas: "coderdojo, projects"
hardware: "electronic-components"
software: ""
last_tested: "2018-06-12"
steps:
  - 
    title: Introducción
  - 
    title: Prueba tus LED
  - 
    title: Cose tu circuito
  - 
    title: Escribe tu propio código
  - 
    title: Color y luz
  - 
    title: Luces parpadeantes
  - 
    title: Anima!
  - 
    title: Diversión colorida
