---
title: Chemise Techno
hero_image: images/banner.png
description: Apprendre à contrôler les LED avec du code tout en réalisant un projet
  portatif
theme: violet
version: 3.0.0
listed: true
copyedit: true
interests: wearable-technology
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-1, community-0
technologies: electronic-components
site_areas: coderdojo, projects
hardware: electronic-components
software: ''
last_tested: '2018-06-12'
steps:
- title: Introduction
- title: Tester tes LED
- title: Coudre ton circuit
  completion:
  - engaged
- title: Écrire ton propre code
- title: Couleur et lumière
- title: Lumières clignotantes
- title: Animer !
- title: Arc-en-ciel amusant
  completion:
  - internal
